### ISSUE TITLE
Docker for the service

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/detectproj.mzk.cz#3]
Implement Dockerfile with the service, also available in binary form on Docker Hub.

The Docker will implement:
- [x] Compilation of libalgo
- [ ] New CGI in C++ #2
- [ ] Apache etc a la https://github.com/moravianlibrary/iipsrv/tree/docker/dockerfile

One docker run with a shared directory with SQLite (created if it does not exist) should be able to serve the requests equally to http://detectproj.mzk.cz/

**Comment by dudaerich** [comment]
See https://registry.hub.docker.com/u/moravianlibrary/detectproj.mzk.cz/
