### ISSUE TITLE
Sample JavaScript viewer

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/detectproj.mzk.cz#4]
- [x] A map with Graticule overlay layer.
- [x] List of detected parameters (ideally in Proj4 compatible string).
- [x] Switching between the top 3 detected parameters. 
- [ ] Marc format for type of projection.

**Comment by klokan** [comment]
Integration with StareMapy.cz done already via a hack. Proper implementation needs https://github.com/klokan/georeferencer/issues/114

This ticket should include a sample viewer for the test Zoomify map:
http://moravianlibrary.georeferencer.com/map/2kkkepIJCPtJnogMl4NDB6/201411030439-XDuIll/visualize

**Comment by klokan** [comment]
Implementation of the viewer as the single index.html has a filed with sample JSON data and "Submit" button - which will post to the CGI for calculation and show the sample map in OpenLayers.

**Comment by dudaerich** [comment]
http://detectproj.mzk.cz/
