### ISSUE TITLE
Pull requests to bayertom/libalgo

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/detectproj.mzk.cz#5]
There should be two pull request:
- [x] export to GeoJSON
- [x] loadPointsFrom
  (choose better names - and describe in the PULL request what has been done).

Please put in comment here the links to these two pull requests.

**Comment by dudaerich** [comment]
I created pull request that amends libalgo project to use with Automake tools, see https://github.com/bayertom/libalgo/pull/7. This pull request changes the structure of the project so we have to wait until it will be merged.

**Comment by dudaerich** [comment]
https://github.com/bayertom/libalgo/pull/8
https://github.com/bayertom/libalgo/pull/9

**Comment by klokan** [comment]
Thanks!
