### ISSUE TITLE
Interested points filter - documentation

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/detectproj.mzk.cz#6]
We have implemented a method which is filtering the input points.

Once libalgo is faster (https://github.com/bayertom/libalgo/issues/3 is closed) we should probably remove this edits.

@dudaerich - please document how to remove the filter - and post links to commits in which it was implemented.

**Comment by dudaerich** [comment]
For removing the filter you must
- comment out these lines https://github.com/moravianlibrary/detectproj.mzk.cz/blob/b8e8bcfdb7164ce203de53897ed5ead341313dda/src/main.cpp#L234-L242,
- replace this line https://github.com/moravianlibrary/detectproj.mzk.cz/blob/b8e8bcfdb7164ce203de53897ed5ead341313dda/src/main.cpp#L246 for

``` c++
detectproj(test_points, ref_points, ss);
```

The commit that adds the filter: https://github.com/moravianlibrary/detectproj.mzk.cz/commit/b8e8bcfdb7164ce203de53897ed5ead341313dda
